from pathlib import Path

DEBUG = False

FPS = 60
BACKGROUND = (255,255,255)  # White
BROWN = (131, 101, 57)  # Brown
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
BASE_SPEED = 200
GROUND_HEIGHT = 100
GRAVITY = 12

PLAYER_SIZE = (32,32)
PLAYER_START = (SCREEN_WIDTH / 2, SCREEN_HEIGHT - GROUND_HEIGHT - PLAYER_SIZE[0] / 2)
PLAYER_HITBOX_INFLATE = (-14, -9)


BULLET_SIZE = (7,7)
BULLET_ROT_SPEED = -8
BULLET_SPEED = 100

TILE_SIZE = (32,32)
IMG_EXT = '.png'

PLAYER_SPRITES_DIR = Path('assets/Sunny-land-files/Assets/Characters/Foxy/Sprites')


# LEGACY
ROT_SPEED = -5